// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CallPublic
 */
export type CallPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Ward Id
     */
    ward_id: string;
    /**
     * Call Task Id
     */
    call_task_id: string;
    /**
     * Routine Id
     */
    routine_id: string;
    /**
     * Routine
     */
    routine: {
        [key: string]: string;
    };
    /**
     * Status
     */
    status: string;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Duration Sec
     */
    duration_sec: number;
    /**
     * Attempt No
     */
    attempt_no: number;
    result?: CallResultPublic | null;
    /**
     * Turns
     */
    turns?: Array<CallTurnPublic>;
};

/**
 * CallResultPublic
 */
export type CallResultPublic = {
    /**
     * Outcome
     */
    outcome: string;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Transcript Full
     */
    transcript_full: string;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * CallTaskPublic
 */
export type CallTaskPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Routine Id
     */
    routine_id: string;
    /**
     * Scheduled At
     */
    scheduled_at: string;
    /**
     * Attempt No
     */
    attempt_no: number;
    /**
     * Max Attempts
     */
    max_attempts: number;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * CallTasksPublic
 */
export type CallTasksPublic = {
    /**
     * Data
     */
    data: Array<CallTaskPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * CallTurnPublic
 */
export type CallTurnPublic = {
    /**
     * Turn No
     */
    turn_no: number;
    /**
     * Question
     */
    question: string;
    /**
     * Speech Result
     */
    speech_result: string;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Parsed
     */
    parsed: string;
};

/**
 * CallsPublic
 */
export type CallsPublic = {
    /**
     * Data
     */
    data: Array<CallPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * DailyStats
 */
export type DailyStats = {
    /**
     * Took
     */
    took: number;
    /**
     * Total
     */
    total: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * MedicationPublic
 */
export type MedicationPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Dosage
     */
    dosage: string;
    /**
     * Form
     */
    form?: string | null;
    /**
     * Instructions
     */
    instructions?: string | null;
    /**
     * Generic Name (FDA / INN)
     */
    generic_name?: string | null;
    /**
     * Raw openFDA drug label data
     */
    fda_raw?: string | null;
    /**
     * Polish AI summary of the medication
     */
    ai_summary?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * MedicationUpdate
 */
export type MedicationUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Dosage
     */
    dosage?: string | null;
    /**
     * Form
     */
    form?: string | null;
    /**
     * Instructions
     */
    instructions?: string | null;
    /**
     * Generic Name (FDA / INN)
     */
    generic_name?: string | null;
    /**
     * Raw openFDA drug label data
     */
    fda_raw?: string | null;
    /**
     * Polish AI summary of the medication
     */
    ai_summary?: string | null;
};

/**
 * MedicationsPublic
 */
export type MedicationsPublic = {
    /**
     * Data
     */
    data: Array<MedicationPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * RoutineCreate
 */
export type RoutineCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Time Of Day
     */
    time_of_day: string;
    /**
     * Days
     */
    days?: string;
    /**
     * Items
     */
    items?: Array<RoutineItemCreate>;
    /**
     * Depends On
     */
    depends_on?: Array<string>;
};

/**
 * RoutineDependencyPublic
 */
export type RoutineDependencyPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: string;
};

/**
 * RoutineItemCreate
 */
export type RoutineItemCreate = {
    /**
     * Medication Id
     */
    medication_id: string;
    /**
     * Amount Label
     */
    amount_label: string;
};

/**
 * RoutineItemPublic
 */
export type RoutineItemPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Medication Id
     */
    medication_id: string;
    /**
     * Amount Label
     */
    amount_label: string;
    medication?: MedicationPublic | null;
};

/**
 * RoutinePublic
 */
export type RoutinePublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Time Of Day
     */
    time_of_day: string;
    /**
     * Days
     */
    days?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Ward Id
     */
    ward_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Items
     */
    items?: Array<RoutineItemPublic>;
    /**
     * Depends On
     */
    depends_on?: Array<RoutineDependencyPublic>;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * RoutineUpdate
 */
export type RoutineUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Time Of Day
     */
    time_of_day?: string | null;
    /**
     * Days
     */
    days?: string | null;
    /**
     * Items
     */
    items?: Array<RoutineItemCreate> | null;
    /**
     * Depends On
     */
    depends_on?: Array<string> | null;
};

/**
 * RoutinesPublic
 */
export type RoutinesPublic = {
    /**
     * Data
     */
    data: Array<RoutinePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VoiceEvent
 */
export type VoiceEvent = {
    /**
     * Event
     */
    event: 'summary' | 'terminal';
    /**
     * Sid
     */
    sid: string;
    /**
     * Medications
     */
    medications?: {
        [key: string]: 0 | 1;
    };
    /**
     * Transcript
     */
    transcript?: string;
    /**
     * Notes
     */
    notes?: string;
    /**
     * Status
     */
    status?: 'completed' | 'busy' | 'failed' | 'no-answer' | 'canceled' | null;
    /**
     * Duration Sec
     */
    duration_sec?: number;
};

/**
 * WardCreate
 */
export type WardCreate = {
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Phone E164
     */
    phone_e164: string;
    /**
     * Tz
     */
    tz?: string;
};

/**
 * WardPublic
 */
export type WardPublic = {
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Phone E164
     */
    phone_e164: string;
    /**
     * Tz
     */
    tz?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Active
     */
    active: boolean;
    /**
     * Caregiver Id
     */
    caregiver_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * WardStatsPublic
 */
export type WardStatsPublic = {
    today: DailyStats;
    /**
     * Week Pct
     */
    week_pct: number;
};

/**
 * WardUpdate
 */
export type WardUpdate = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Phone E164
     */
    phone_e164?: string | null;
    /**
     * Tz
     */
    tz?: string | null;
};

/**
 * WardsPublic
 */
export type WardsPublic = {
    /**
     * Data
     */
    data: Array<WardPublic>;
    /**
     * Count
     */
    count: number;
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type itemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type itemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemsError = itemsReadItemsErrors[keyof itemsReadItemsErrors];

export type itemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type itemsReadItemsResponse = itemsReadItemsResponses[keyof itemsReadItemsResponses];

export type itemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type itemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsCreateItemError = itemsCreateItemErrors[keyof itemsCreateItemErrors];

export type itemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsCreateItemResponse = itemsCreateItemResponses[keyof itemsCreateItemResponses];

export type itemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsDeleteItemError = itemsDeleteItemErrors[keyof itemsDeleteItemErrors];

export type itemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type itemsDeleteItemResponse = itemsDeleteItemResponses[keyof itemsDeleteItemResponses];

export type itemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemError = itemsReadItemErrors[keyof itemsReadItemErrors];

export type itemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsReadItemResponse = itemsReadItemResponses[keyof itemsReadItemResponses];

export type itemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsUpdateItemError = itemsUpdateItemErrors[keyof itemsUpdateItemErrors];

export type itemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsUpdateItemResponse = itemsUpdateItemResponses[keyof itemsUpdateItemResponses];

export type medicationsReadMedicationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/medications/';
};

export type medicationsReadMedicationsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type medicationsReadMedicationsError = medicationsReadMedicationsErrors[keyof medicationsReadMedicationsErrors];

export type medicationsReadMedicationsResponses = {
    /**
     * Successful Response
     */
    200: MedicationsPublic;
};

export type medicationsReadMedicationsResponse = medicationsReadMedicationsResponses[keyof medicationsReadMedicationsResponses];

export type medicationsDeleteMedicationData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/medications/{id}';
};

export type medicationsDeleteMedicationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type medicationsDeleteMedicationError = medicationsDeleteMedicationErrors[keyof medicationsDeleteMedicationErrors];

export type medicationsDeleteMedicationResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type medicationsDeleteMedicationResponse = medicationsDeleteMedicationResponses[keyof medicationsDeleteMedicationResponses];

export type medicationsReadMedicationData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/medications/{id}';
};

export type medicationsReadMedicationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type medicationsReadMedicationError = medicationsReadMedicationErrors[keyof medicationsReadMedicationErrors];

export type medicationsReadMedicationResponses = {
    /**
     * Successful Response
     */
    200: MedicationPublic;
};

export type medicationsReadMedicationResponse = medicationsReadMedicationResponses[keyof medicationsReadMedicationResponses];

export type medicationsUpdateMedicationData = {
    body: MedicationUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/medications/{id}';
};

export type medicationsUpdateMedicationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type medicationsUpdateMedicationError = medicationsUpdateMedicationErrors[keyof medicationsUpdateMedicationErrors];

export type medicationsUpdateMedicationResponses = {
    /**
     * Successful Response
     */
    200: MedicationPublic;
};

export type medicationsUpdateMedicationResponse = medicationsUpdateMedicationResponses[keyof medicationsUpdateMedicationResponses];

export type wardsReadWardsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/wards/';
};

export type wardsReadWardsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type wardsReadWardsError = wardsReadWardsErrors[keyof wardsReadWardsErrors];

export type wardsReadWardsResponses = {
    /**
     * Successful Response
     */
    200: WardsPublic;
};

export type wardsReadWardsResponse = wardsReadWardsResponses[keyof wardsReadWardsResponses];

export type wardsCreateWardData = {
    body: WardCreate;
    path?: never;
    query?: never;
    url: '/api/v1/wards/';
};

export type wardsCreateWardErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type wardsCreateWardError = wardsCreateWardErrors[keyof wardsCreateWardErrors];

export type wardsCreateWardResponses = {
    /**
     * Successful Response
     */
    200: WardPublic;
};

export type wardsCreateWardResponse = wardsCreateWardResponses[keyof wardsCreateWardResponses];

export type wardsDeleteWardData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/wards/{id}';
};

export type wardsDeleteWardErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type wardsDeleteWardError = wardsDeleteWardErrors[keyof wardsDeleteWardErrors];

export type wardsDeleteWardResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type wardsDeleteWardResponse = wardsDeleteWardResponses[keyof wardsDeleteWardResponses];

export type wardsReadWardData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/wards/{id}';
};

export type wardsReadWardErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type wardsReadWardError = wardsReadWardErrors[keyof wardsReadWardErrors];

export type wardsReadWardResponses = {
    /**
     * Successful Response
     */
    200: WardPublic;
};

export type wardsReadWardResponse = wardsReadWardResponses[keyof wardsReadWardResponses];

export type wardsUpdateWardData = {
    body: WardUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/wards/{id}';
};

export type wardsUpdateWardErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type wardsUpdateWardError = wardsUpdateWardErrors[keyof wardsUpdateWardErrors];

export type wardsUpdateWardResponses = {
    /**
     * Successful Response
     */
    200: WardPublic;
};

export type wardsUpdateWardResponse = wardsUpdateWardResponses[keyof wardsUpdateWardResponses];

export type routinesReadRoutinesForWardData = {
    body?: never;
    path: {
        /**
         * Ward Id
         */
        ward_id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/wards/{ward_id}/routines';
};

export type routinesReadRoutinesForWardErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type routinesReadRoutinesForWardError = routinesReadRoutinesForWardErrors[keyof routinesReadRoutinesForWardErrors];

export type routinesReadRoutinesForWardResponses = {
    /**
     * Successful Response
     */
    200: RoutinesPublic;
};

export type routinesReadRoutinesForWardResponse = routinesReadRoutinesForWardResponses[keyof routinesReadRoutinesForWardResponses];

export type routinesCreateRoutineData = {
    body: RoutineCreate;
    path: {
        /**
         * Ward Id
         */
        ward_id: string;
    };
    query?: never;
    url: '/api/v1/wards/{ward_id}/routines';
};

export type routinesCreateRoutineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type routinesCreateRoutineError = routinesCreateRoutineErrors[keyof routinesCreateRoutineErrors];

export type routinesCreateRoutineResponses = {
    /**
     * Successful Response
     */
    200: RoutinePublic;
};

export type routinesCreateRoutineResponse = routinesCreateRoutineResponses[keyof routinesCreateRoutineResponses];

export type routinesDeleteRoutineData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/routines/{id}';
};

export type routinesDeleteRoutineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type routinesDeleteRoutineError = routinesDeleteRoutineErrors[keyof routinesDeleteRoutineErrors];

export type routinesDeleteRoutineResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type routinesDeleteRoutineResponse = routinesDeleteRoutineResponses[keyof routinesDeleteRoutineResponses];

export type routinesUpdateRoutineData = {
    body: RoutineUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/routines/{id}';
};

export type routinesUpdateRoutineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type routinesUpdateRoutineError = routinesUpdateRoutineErrors[keyof routinesUpdateRoutineErrors];

export type routinesUpdateRoutineResponses = {
    /**
     * Successful Response
     */
    200: RoutinePublic;
};

export type routinesUpdateRoutineResponse = routinesUpdateRoutineResponses[keyof routinesUpdateRoutineResponses];

export type routinesApproveRoutineData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/routines/{id}/approve';
};

export type routinesApproveRoutineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type routinesApproveRoutineError = routinesApproveRoutineErrors[keyof routinesApproveRoutineErrors];

export type routinesApproveRoutineResponses = {
    /**
     * Successful Response
     */
    200: RoutinePublic;
};

export type routinesApproveRoutineResponse = routinesApproveRoutineResponses[keyof routinesApproveRoutineResponses];

export type routinesPauseRoutineData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/routines/{id}/pause';
};

export type routinesPauseRoutineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type routinesPauseRoutineError = routinesPauseRoutineErrors[keyof routinesPauseRoutineErrors];

export type routinesPauseRoutineResponses = {
    /**
     * Successful Response
     */
    200: RoutinePublic;
};

export type routinesPauseRoutineResponse = routinesPauseRoutineResponses[keyof routinesPauseRoutineResponses];

export type callsCreateTestCallData = {
    body?: never;
    path: {
        /**
         * Ward Id
         */
        ward_id: string;
    };
    query?: {
        /**
         * Routine Id
         */
        routine_id?: string | null;
    };
    url: '/api/v1/wards/{ward_id}/test-call';
};

export type callsCreateTestCallErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type callsCreateTestCallError = callsCreateTestCallErrors[keyof callsCreateTestCallErrors];

export type callsCreateTestCallResponses = {
    /**
     * Successful Response
     */
    201: CallTaskPublic;
};

export type callsCreateTestCallResponse = callsCreateTestCallResponses[keyof callsCreateTestCallResponses];

export type callsReadCallTasksData = {
    body?: never;
    path: {
        /**
         * Ward Id
         */
        ward_id: string;
    };
    query?: {
        /**
         * Status
         */
        status?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * From
         */
        from?: string | null;
        /**
         * To
         */
        to?: string | null;
    };
    url: '/api/v1/wards/{ward_id}/call-tasks';
};

export type callsReadCallTasksErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type callsReadCallTasksError = callsReadCallTasksErrors[keyof callsReadCallTasksErrors];

export type callsReadCallTasksResponses = {
    /**
     * Successful Response
     */
    200: CallTasksPublic;
};

export type callsReadCallTasksResponse = callsReadCallTasksResponses[keyof callsReadCallTasksResponses];

export type callsReadCallsData = {
    body?: never;
    path: {
        /**
         * Ward Id
         */
        ward_id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/wards/{ward_id}/calls';
};

export type callsReadCallsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type callsReadCallsError = callsReadCallsErrors[keyof callsReadCallsErrors];

export type callsReadCallsResponses = {
    /**
     * Successful Response
     */
    200: CallsPublic;
};

export type callsReadCallsResponse = callsReadCallsResponses[keyof callsReadCallsResponses];

export type callsReadCallData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/calls/{id}';
};

export type callsReadCallErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type callsReadCallError = callsReadCallErrors[keyof callsReadCallErrors];

export type callsReadCallResponses = {
    /**
     * Successful Response
     */
    200: CallPublic;
};

export type callsReadCallResponse = callsReadCallResponses[keyof callsReadCallResponses];

export type callsReadStatsData = {
    body?: never;
    path: {
        /**
         * Ward Id
         */
        ward_id: string;
    };
    query?: never;
    url: '/api/v1/wards/{ward_id}/stats';
};

export type callsReadStatsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type callsReadStatsError = callsReadStatsErrors[keyof callsReadStatsErrors];

export type callsReadStatsResponses = {
    /**
     * Successful Response
     */
    200: WardStatsPublic;
};

export type callsReadStatsResponse = callsReadStatsResponses[keyof callsReadStatsResponses];

export type voicePersistVoiceEventData = {
    body: VoiceEvent;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/internal/calls/{task_id}/events';
};

export type voicePersistVoiceEventErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type voicePersistVoiceEventError = voicePersistVoiceEventErrors[keyof voicePersistVoiceEventErrors];

export type voicePersistVoiceEventResponses = {
    /**
     * Response Voice-Persist Voice Event
     *
     * Successful Response
     */
    200: {
        [key: string]: boolean;
    };
};

export type voicePersistVoiceEventResponse = voicePersistVoiceEventResponses[keyof voicePersistVoiceEventResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
