"""complete care routine call models

Revision ID: 62a457a0e2fd
Revises: 4bca66fa5988
Create Date: 2026-10-03 17:57:19.999851

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "62a457a0e2fd"
down_revision = "4bca66fa5988"
branch_labels = None
depends_on = None


def upgrade():
    # Existing installations may contain rows without creation timestamps.
    for table_name in ("user", "item", "medication", "ward", "routine"):
        table = sa.table(
            table_name, sa.column("created_at", sa.DateTime(timezone=True))
        )
        op.execute(
            table.update()
            .where(table.c.created_at.is_(None))
            .values(created_at=sa.func.now())
        )
        op.alter_column(table_name, "created_at", server_default=sa.text("now()"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calltask",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("routine_id", sa.Uuid(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'in_progress', 'completed', 'failed', 'cancelled')",
            name="ck_calltask_status",
        ),
        sa.CheckConstraint(
            "attempt_no >= 1 AND max_attempts >= attempt_no",
            name="ck_calltask_attempts",
        ),
        sa.ForeignKeyConstraint(["routine_id"], ["routine.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "routine_id", "scheduled_at", "attempt_no", name="uq_calltask_occurrence"
        ),
    )
    op.create_index(
        op.f("ix_calltask_routine_id"), "calltask", ["routine_id"], unique=False
    )
    op.create_index(
        "ix_calltask_status_scheduled_at",
        "calltask",
        ["status", "scheduled_at"],
        unique=False,
    )
    op.create_table(
        "call",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("call_task_id", sa.Uuid(), nullable=False),
        sa.Column(
            "twilio_call_sid",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=True,
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("duration_sec", sa.Integer(), nullable=False),
        sa.Column(
            "recording_url",
            sqlmodel.sql.sqltypes.AutoString(length=2048),
            nullable=True,
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'ringing', 'in-progress', 'completed', 'busy', 'failed', 'no-answer', 'canceled')",
            name="ck_call_status",
        ),
        sa.CheckConstraint("duration_sec >= 0", name="ck_call_duration"),
        sa.ForeignKeyConstraint(["call_task_id"], ["calltask.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("call_task_id"),
        sa.UniqueConstraint("twilio_call_sid"),
    )
    op.create_table(
        "callresult",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("call_id", sa.Uuid(), nullable=False),
        sa.Column(
            "outcome", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "transcript_full", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.CheckConstraint(
            "outcome IN ('took', 'not_taken', 'unclear', 'no_answer')",
            name="ck_callresult_outcome",
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name="ck_callresult_confidence"
        ),
        sa.ForeignKeyConstraint(["call_id"], ["call.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("call_id"),
    )
    op.create_table(
        "callturn",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("call_id", sa.Uuid(), nullable=False),
        sa.Column("turn_no", sa.Integer(), nullable=False),
        sa.Column("question", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("speech_result", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "parsed", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.CheckConstraint(
            "parsed IN ('yes', 'no', 'unclear')", name="ck_callturn_parsed"
        ),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name="ck_callturn_confidence"),
        sa.CheckConstraint("turn_no >= 1", name="ck_callturn_number"),
        sa.ForeignKeyConstraint(["call_id"], ["call.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("call_id", "turn_no", name="uq_callturn_number"),
    )
    op.create_index(op.f("ix_callturn_call_id"), "callturn", ["call_id"], unique=False)
    op.create_table(
        "escalationevent",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("call_result_id", sa.Uuid(), nullable=False),
        sa.Column("caregiver_id", sa.Uuid(), nullable=False),
        sa.Column(
            "channel", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.CheckConstraint(
            "channel IN ('email', 'sms')", name="ck_escalationevent_channel"
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'sent', 'failed')", name="ck_escalationevent_status"
        ),
        sa.ForeignKeyConstraint(
            ["call_result_id"], ["callresult.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["caregiver_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_escalationevent_call_result_id"),
        "escalationevent",
        ["call_result_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_escalationevent_caregiver_id"),
        "escalationevent",
        ["caregiver_id"],
        unique=False,
    )
    op.add_column(
        "item",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "item",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.add_column(
        "medication",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "medication",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.add_column(
        "routine",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "routine",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.create_check_constraint(
        "ck_routine_status", "routine", "status IN ('draft', 'approved', 'paused')"
    )
    op.add_column(
        "routinedependency",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "routinedependency",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "routineitem",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "routineitem",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "user",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.add_column(
        "ward",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "ward",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    for table_name in ("user", "item", "medication", "ward", "routine"):
        op.alter_column(table_name, "created_at", server_default=None)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ward",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_column("ward", "updated_at")
    op.alter_column(
        "user",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_column("user", "updated_at")
    op.drop_column("routineitem", "updated_at")
    op.drop_column("routineitem", "created_at")
    op.drop_column("routinedependency", "updated_at")
    op.drop_column("routinedependency", "created_at")
    op.drop_constraint("ck_routine_status", "routine", type_="check")
    op.alter_column(
        "routine",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_column("routine", "updated_at")
    op.alter_column(
        "medication",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_column("medication", "updated_at")
    op.alter_column(
        "item",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_column("item", "updated_at")
    op.drop_index(op.f("ix_escalationevent_caregiver_id"), table_name="escalationevent")
    op.drop_index(
        op.f("ix_escalationevent_call_result_id"), table_name="escalationevent"
    )
    op.drop_table("escalationevent")
    op.drop_index(op.f("ix_callturn_call_id"), table_name="callturn")
    op.drop_table("callturn")
    op.drop_table("callresult")
    op.drop_table("call")
    op.drop_index("ix_calltask_status_scheduled_at", table_name="calltask")
    op.drop_index(op.f("ix_calltask_routine_id"), table_name="calltask")
    op.drop_table("calltask")
    # ### end Alembic commands ###
