"""add ward table

Revision ID: 77b7a1152d55
Revises: fd3710ee30b8
Create Date: 2026-10-03 14:29:32.456899

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '77b7a1152d55'
down_revision = 'fd3710ee30b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ward',
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone_e164', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('tz', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('caregiver_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ward_caregiver_id'), 'ward', ['caregiver_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ward_caregiver_id'), table_name='ward')
    op.drop_table('ward')
    # ### end Alembic commands ###
